version: '{build}'
image: 'Visual Studio 2017'

clone_folder: 'c:\go\src\github.com\umschlag\umschlag-docs'

environment:
  DOCKER_USERNAME:
    secure: '4YzzahbEiMZQJpOCOd1LAw=='
  DOCKER_PASSWORD:
    secure: 'VqO/G3Zfslu6zSLdwHKO+Q=='

install:
  - ps: |
      Install-Product node ''
  - ps: |
      choco install make
  - ps: |
      choco install hugo
  - ps: |
      docker version
      hugo version

build_script:
  - cmd: |
      make assets
  - cmd: |
      make build
  - cmd: |
      docker pull microsoft/nanoserver:10.0.14393.1593
      docker build -f Dockerfile.windows -t umschlag/umschlag-docs:windows .

test_script:
  - cmd: |
      docker run --rm umschlag/umschlag-docs:windows caddy.exe -version

deploy_script:
  - ps: |
      if ( $env:APPVEYOR_PULL_REQUEST_NUMBER ) {
        Write-Host Nothing to deploy.
      } else {
        docker login --username $env:DOCKER_USERNAME --password $env:DOCKER_PASSWORD

        if ( $env:APPVEYOR_REPO_TAG -eq 'true' ) {
          $major,$minor,$patch = $env:APPVEYOR_REPO_TAG_NAME.substring(1).split('.')

          docker push umschlag/umschlag-docs:windows

          docker tag umschlag/umschlag-docs:windows umschlag/umschlag-docs:$major.$minor.$patch-windows
          docker push umschlag/umschlag-docs:$major.$minor.$patch-windows

          docker tag umschlag/umschlag-docs:windows umschlag/umschlag-docs:$major.$minor-windows
          docker push umschlag/umschlag-docs:$major.$minor-windows

          docker tag umschlag/umschlag-docs:windows umschlag/umschlag-docs:$major-windows
          docker push umschlag/umschlag-docs:$major-windows
        } else {
          if ( $env:APPVEYOR_REPO_BRANCH -eq 'master' ) {
            docker push umschlag/umschlag-docs:windows
          }
        }
      }
