workspace:
  base: /srv/app
  path: src/github.com/umschlag/umschlag-docs

branches:
  - master

pipeline:
  cache-restore:
    image: plugins/s3-cache:1
    pull: true
    secrets: [ cache_s3_endpoint, cache_s3_access_key, cache_s3_secret_key ]
    restore: true
    when:
      local: false

  frontend-prepare:
    image: webhippie/nodejs:latest
    pull: true
    commands:
      - yarn install

  frontend-lint:
    image: webhippie/nodejs:latest
    pull: true
    group: frontend
    commands:
      - yarn run lint

  frontend-build:
    image: webhippie/nodejs:latest
    pull: true
    group: frontend
    commands:
      - yarn run build

  backend-build:
    image: webhippie/hugo:latest
    pull: true
    group: backend
    commands:
      - make build

  docker-amd64:
    image: plugins/docker:17.05
    pull: true
    group: docker
    secrets: [ docker_username, docker_password ]
    repo: umschlag/umschlag-docs
    auto_tag: true
    auto_tag_suffix: amd64
    when:
      event: [push, tag]
      branch: master

  docker-i386:
    image: plugins/docker:17.05
    pull: true
    group: docker
    secrets: [ docker_username, docker_password ]
    repo: umschlag/umschlag-docs
    dockerfile: Dockerfile.i386
    auto_tag: true
    auto_tag_suffix: i386
    when:
      event: [push, tag]
      branch: master

  docker-arm64:
    image: plugins/docker:17.05
    pull: true
    group: docker
    secrets: [ docker_username, docker_password ]
    repo: umschlag/umschlag-docs
    dockerfile: Dockerfile.arm64
    auto_tag: true
    auto_tag_suffix: arm64
    when:
      event: [push, tag]
      branch: master

  docker-arm:
    image: plugins/docker:17.05
    pull: true
    group: docker
    secrets: [ docker_username, docker_password ]
    repo: umschlag/umschlag-docs
    dockerfile: Dockerfile.arm
    auto_tag: true
    auto_tag_suffix: arm
    when:
      event: [push, tag]
      branch: master

  docker-manifests:
    image: plugins/manifest:1
    pull: true
    secrets: [ docker_username, docker_password ]
    spec: manifest.yml
    auto_tag: true
    ignore_missing: true
    when:
      event: [ push, tag ]
      branch: master

  docker-microbadger:
    image: plugins/webhook:1
    pull: true
    secrets:
      - source: microbadger_token
        target: plugin_urls
    when:
      event: [ push, tag ]
      branch: master

  cache-rebuild:
    image: plugins/s3-cache:1
    pull: true
    secrets: [ cache_s3_endpoint, cache_s3_access_key, cache_s3_secret_key ]
    rebuild: true
    mount:
      - node_modules
    when:
      local: false
      event: [ push ]
      branch: master

  cache-flush:
    image: plugins/s3-cache:1
    pull: true
    secrets: [ cache_s3_endpoint, cache_s3_access_key, cache_s3_secret_key ]
    flush: true
    flush_age: 14
    when:
      local: false
      event: [ push ]
      branch: master

  notify-matrix:
    image: plugins/matrix:1
    pull: true
    secrets: [ matrix_roomid, matrix_username, matrix_password ]
    when:
      local: false
      events: [ push, tag ]
      status: [ changed, failure ]
