pipeline:
  build:
    image: webhippie/alpine:latest
    commands:
      - apk -U add hugo@testing
      - hugo --cleanDestinationDir

  publish:
    image: dronecommunity/pubstorm
    when:
      event: push
      branch: master

  gitter:
    image: plugins/gitter