workspace:
  base: /srv/app
  path: src/github.com/umschlag/umschlag-docs

branches:
  - master

pipeline:
  cache-restore:
    image: plugins/s3-cache:1
    pull: true
    secrets: [ cache_s3_endpoint, cache_s3_access_key, cache_s3_secret_key ]
    restore: true
    when:
      local: false

  frontend-prepare:
    image: webhippie/nodejs:latest
    pull: true
    commands:
      - yarn install

  frontend-lint:
    image: webhippie/nodejs:latest
    pull: true
    group: frontend
    commands:
      - yarn run lint

  frontend-build:
    image: webhippie/nodejs:latest
    pull: true
    group: frontend
    commands:
      - yarn run build

  backend-build:
    image: webhippie/hugo:latest
    pull: true
    group: backend
    commands:
      - make build

  publish-netlify:
    image: lucap/drone-netlify:latest
    pull: true
    secrets: [ netlify_token ]
    site_id: 75a2b3b5-f6f6-4885-9ece-4347c40bd65a
    path: public/
    when:
      event: [ push, tag ]
      branch: master

  cache-rebuild:
    image: plugins/s3-cache:1
    pull: true
    secrets: [ cache_s3_endpoint, cache_s3_access_key, cache_s3_secret_key ]
    rebuild: true
    mount:
      - node_modules
    when:
      local: false
      event: [ push ]
      branch: master

  cache-flush:
    image: plugins/s3-cache:1
    pull: true
    secrets: [ cache_s3_endpoint, cache_s3_access_key, cache_s3_secret_key ]
    flush: true
    flush_age: 14
    when:
      local: false
      event: [ push ]
      branch: master

  notify-matrix:
    image: plugins/matrix:1
    pull: true
    secrets: [ matrix_roomid, matrix_username, matrix_password ]
    when:
      local: false
      events: [ push, tag ]
      status: [ changed, failure ]
