pipeline:
  build:
    image: webhippie/alpine:latest
    commands:
      - apk -U add hugo@testing
      - hugo --cleanDestinationDir

  checks:
    image: webhippie/linkchecker:latest
    commands:
      - linkchecker -v http://localhost:8080

  publish:
    image: dronecommunity/pubstorm
    when:
      event: push
      branch: master

  docker:
    image: plugins/docker
    repo: umschlag/umschlag-docs
    tags: [ '${TAG}' ]
    when:
      event: tag
      branch: refs/tags/*

  docker:
    image: plugins/docker
    repo: umschlag/umschlag-docs
    tags: [ 'latest' ]
    when:
      event: push
      branch: master

  gitter:
    image: umschlag/gitter

services:
  server:
    image: webhippie/caddy:latest
    command: [/usr/sbin/caddy, -port, 8080, -root, /drone/src/public]
