---
kind: pipeline
name: testing

platform:
  os: linux
  arch: amd64

steps:
- name: prepare
  image: webhippie/nodejs:latest
  pull: always
  commands:
  - yarn install --frozen-lockfile

- name: lint
  image: webhippie/nodejs:latest
  pull: always
  commands:
  - yarn lint
  depends_on:
  - prepare

- name: build
  image: webhippie/nodejs:latest
  pull: always
  commands:
  - yarn build
  depends_on:
  - prepare

- name: hugo
  image: webhippie/hugo:latest
  pull: always
  commands:
  - make build
  depends_on:
  - lint
  - build

- name: publish
  image: lucap/drone-netlify:latest
  pull: always
  settings:
    token:
      from_secret: netlify_token
    site_id: 75a2b3b5-f6f6-4885-9ece-4347c40bd65a
    path: public/
  when:
    event:
      exclude:
      - pull_request
  depends_on:
  - hugo

- name: notify
  image: plugins/matrix:1
  pull: always
  settings:
    username:
      from_secret: matrix_username
    password:
      from_secret: matrix_password
    roomid:
      from_secret: matrix_roomid
  when:
    event:
    - push
    - tag
    status:
    - failure
  depends_on:
  - prepare
  - lint
  - build
  - hugo
  - publish

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**
