pipeline:
  build:
    image: webhippie/alpine:latest
    commands:
      - apk -U add git hugo@testing
      - hugo
      - git remote add website https://github.com/umschlag/umschlag.github.com.git

  # TODO: Push to master @ github.com/umschlag/umschlag.github.com
