pipeline:
  build:
    image: webhippie/alpine:latest
    commands:
      - apk -U add hugo@testing
      - hugo --cleanDestinationDir

  publish:
    image: drone-community/pubstorm
    when:
      event: push
      branch: master
