pipeline:
  build:
    image: webhippie/alpine:latest
    commands:
      - apk -U add hugo@testing
      - hugo

      - cp -rf public /drone/public
      - rm -rf * .lgtm .gitignore .github .drone*
      - cp -rf /drone/public/* .

  publish:
    image: umschlag/git-push
    branch: master
    remote: https://github.com/umschlag/umschlag.github.com.git
    force: true
    commit: true
    when:
      event: push
      branch: master
