baseurl = "/"
languageCode = "en-us"
title = "Umschlag"
disableKinds = ["RSS"]

[params]
  Description = "Docker distribution management system"
  Author = "Umschlag Team"
  Website = "https://umschlag.webhippie.de"
  Github = "umschlag"
